# Generated by Django 4.0.3 on 2022-03-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='number',
            new_name='id',
        ),
    ]
