# Generated by Django 4.0.3 on 2022-03-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0002_rename_number_place_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.CharField(max_length=100)),
                ('opening_time', models.DateTimeField()),
                ('picked_up', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.CharField(max_length=100)),
                ('opening_time', models.DateTimeField()),
                ('codes', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
