# Generated by Django 4.0.3 on 2022-04-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0002_kill_message_player_delete_customuser_kill_killer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kill',
            name='killer',
        ),
        migrations.AddField(
            model_name='kill',
            name='killer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='killer', to='hg_app.player'),
        ),
        migrations.RemoveField(
            model_name='kill',
            name='victim',
        ),
        migrations.AddField(
            model_name='kill',
            name='victim',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='hg_app.player'),
        ),
        migrations.CreateModel(
            name='HasPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ManyToManyField(to='hg_app.package')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hg_app.player')),
            ],
        ),
    ]
