# Generated by Django 4.0.3 on 2022-04-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0003_remove_kill_killer_kill_killer_remove_kill_victim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hg_app.player')),
                ('point', models.ManyToManyField(to='hg_app.package')),
            ],
        ),
        migrations.CreateModel(
            name='HasMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ManyToManyField(to='hg_app.package')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hg_app.player')),
            ],
        ),
    ]
