# Generated by Django 4.0.3 on 2022-04-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0004_haspoint_hasmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haspackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='haspackage',
            name='player',
        ),
        migrations.RemoveField(
            model_name='haspoint',
            name='player',
        ),
        migrations.RemoveField(
            model_name='haspoint',
            name='point',
        ),
        migrations.AddField(
            model_name='player',
            name='messages',
            field=models.ManyToManyField(to='hg_app.message'),
        ),
        migrations.AddField(
            model_name='player',
            name='packages',
            field=models.ManyToManyField(to='hg_app.package'),
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.ManyToManyField(to='hg_app.point'),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='point',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='HasMessage',
        ),
        migrations.DeleteModel(
            name='HasPackage',
        ),
        migrations.DeleteModel(
            name='HasPoint',
        ),
    ]
