# Generated by Django 4.0.3 on 2022-04-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0005_remove_haspackage_package_remove_haspackage_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kill',
            name='killer',
        ),
        migrations.AddField(
            model_name='player',
            name='kills',
            field=models.ManyToManyField(to='hg_app.kill'),
        ),
    ]
