# Generated by Django 4.0.3 on 2022-04-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0006_remove_kill_killer_player_kills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='kills',
        ),
        migrations.AddField(
            model_name='kill',
            name='murderer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='killed_victims', to='hg_app.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kill',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murdered_by', to='hg_app.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='messages',
            field=models.ManyToManyField(blank=True, to='hg_app.message'),
        ),
        migrations.AlterField(
            model_name='player',
            name='packages',
            field=models.ManyToManyField(blank=True, to='hg_app.package'),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.ManyToManyField(blank=True, to='hg_app.point'),
        ),
    ]
