# Generated by Django 4.0.4 on 2022-04-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0006_remove_kill_killer_player_kills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='kills',
        ),
        migrations.AddField(
            model_name='kill',
            name='murderer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_kills', to='hg_app.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kill',
            name='stealth_kill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kill',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_deaths', to='hg_app.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='lives',
            field=models.IntegerField(default=3),
        ),
    ]
