# Generated by Django 4.0.3 on 2022-04-24 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0009_alter_package_picked_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='picked_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hg_app.player'),
        ),
    ]
