# Generated by Django 4.0.3 on 2022-04-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0010_alter_package_description_alter_package_picked_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
