# Generated by Django 4.0.3 on 2022-04-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0011_player_score_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
