# Generated by Django 4.0.4 on 2022-05-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0014_alter_package_lat_alter_package_long_alter_point_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='codes',
        ),
        migrations.AddField(
            model_name='point',
            name='picked_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hg_app.player'),
        ),
        migrations.AlterField(
            model_name='package',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='latitude (N)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='long',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='longitude (E)'),
        ),
        migrations.AlterField(
            model_name='point',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='latitude (N)'),
        ),
        migrations.AlterField(
            model_name='point',
            name='long',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='longitude (E)'),
        ),
    ]
