# Generated by Django 4.0.4 on 2022-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0016_point_max_number_of_visits_remove_point_picked_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
