# Generated by Django 4.0.4 on 2022-05-04 09:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hg_app', '0017_alter_point_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=0, srid=4326),
        ),
    ]
